In [1]:
import numpy as np

In [2]:
#From Pyhton List to ndarray
mylist=[10,20,30,40,50]
my_array=np.array(mylist)
print(my_array)

[10 20 30 40 50]


In [4]:
#Multiple sizes
my_matrix=np.array([[1,4,5],[1,7,9],[7,8,9]])
print(my_matrix)

[[1 4 5]
 [1 7 9]
 [7 8 9]]


In [5]:
#Make ndrarray with 0
zero_array=np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#Make ndarray with 1
one_array=np.ones((3,4))
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#Create a spaced array
array_range=np.arange(0,30,3)
print(array_range)

[ 0  3  6  9 12 15 18 21 24 27]


In [8]:
linspace_array=np.linspace(0,5,10)
print(linspace_array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [12]:
new_array=[10,14,18,19,12,18,17]
new_array1=np.array(new_array)
print(new_array1)

print(new_array1.shape)

print(new_array1.dtype)

[10 14 18 19 12 18 17]
(7,)
int32


In [14]:
#Lets make the ndarray
ar=np.array([1,4,7,8,9,10,11,13,15])

#Looking for index
print(ar[0]) #1
print(ar[5]) #10

#Slicing
print(ar[4:8])

1
10
[ 9 10 11 13]


In [15]:
#Add ndarray
array1=np.array([10,20,30])
array2=np.array([40,50,60])

#Array Add
print(array1+array2)

#Subtraction process
print(array2-array1)

#Multiplication
print(array2*array1)

#Division
print(array2/array1)

[50 70 90]
[30 30 30]
[ 400 1000 1800]
[4.  2.5 2. ]


In [17]:
#Universal Functions
array=np.array([1,2,3,7,8,9])

#taking square root
print(np.sqrt(array))


print(np.power(array,3))


print(np.sin(array))

[1.         1.41421356 1.73205081 2.64575131 2.82842712 3.        ]
[  1   8  27 343 512 729]
[0.84147098 0.90929743 0.14112001 0.6569866  0.98935825 0.41211849]


In [18]:
#Reshaping

array=np.array([[14,17,18],
               [96,57,36]])

#Reshape
reshape_arr = array.reshape(3,2)
print(reshape_arr)

[[14 17]
 [18 96]
 [57 36]]


In [21]:
#1. Matematiksel Ufuncs:
A=np.array([10,20,30,40])
B=np.array([70,80,60,90])

print(np.add(A,B))

print(np.subtract(A,B))

print(np.multiply(A,B))

print(np.divide(A,B))

print(np.sqrt(A))

print(np.power(A,2))


[ 80 100  90 130]
[-60 -60 -30 -50]
[ 700 1600 1800 3600]
[0.14285714 0.25       0.5        0.44444444]
[3.16227766 4.47213595 5.47722558 6.32455532]
[ 100  400  900 1600]


In [23]:
#Trigonometri

x=np.array([0,np.pi/2,np.pi])

print(np.sin(x))

print(np.cos(x))

print(np.tan(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [24]:
x=np.array([1,4,6,8,10])

print(np.mean(x))

print(np.median(x))

print(np.std(x))

5.8
6.0
3.1240998703626617


In [26]:
#CONCATENATE

#İki 1D ndarray birleştirme

ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

result=np.concatenate((ar1,ar2))
print(result)


#İki 2D ndarray birleştirme

arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6]])
result=np.concatenate((arr3,arr4))
print(result)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [28]:
import numpy as np

# Dikey olarak birleştirme
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_vertical = np.vstack((arr1, arr2))
print(result_vertical)


# Yatay olarak birleştirme
arr3 = np.array([[7], [8], [9]])
result_horizontal = np.hstack((arr1.reshape(-1, 1), arr3))
print(result_horizontal)


[[1 2 3]
 [4 5 6]]
[[1 7]
 [2 8]
 [3 9]]
